//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationTier.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/DataTier")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/DataTier")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((this.ProfileIDField.Equals(value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/DataTier")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/DataTier")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateChat", ReplyAction="http://tempuri.org/IService/CreateChatResponse")]
        PresentationTier.ServiceReference.Chat CreateChat(PresentationTier.ServiceReference.Chat chat, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateChat", ReplyAction="http://tempuri.org/IService/CreateChatResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat> CreateChatAsync(PresentationTier.ServiceReference.Chat chat, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChatsByName", ReplyAction="http://tempuri.org/IService/GetChatsByNameResponse")]
        PresentationTier.ServiceReference.Chat[] GetChatsByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChatsByName", ReplyAction="http://tempuri.org/IService/GetChatsByNameResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat[]> GetChatsByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateChat", ReplyAction="http://tempuri.org/IService/UpdateChatResponse")]
        bool UpdateChat(PresentationTier.ServiceReference.Chat chat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateChat", ReplyAction="http://tempuri.org/IService/UpdateChatResponse")]
        System.Threading.Tasks.Task<bool> UpdateChatAsync(PresentationTier.ServiceReference.Chat chat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteChat", ReplyAction="http://tempuri.org/IService/DeleteChatResponse")]
        bool DeleteChat(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteChat", ReplyAction="http://tempuri.org/IService/DeleteChatResponse")]
        System.Threading.Tasks.Task<bool> DeleteChatAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonsChats", ReplyAction="http://tempuri.org/IService/GetPersonsChatsResponse")]
        PresentationTier.ServiceReference.Chat[] GetPersonsChats(int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonsChats", ReplyAction="http://tempuri.org/IService/GetPersonsChatsResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat[]> GetPersonsChatsAsync(int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonsInChat", ReplyAction="http://tempuri.org/IService/GetPersonsInChatResponse")]
        PresentationTier.ServiceReference.Profile[] GetPersonsInChat(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPersonsInChat", ReplyAction="http://tempuri.org/IService/GetPersonsInChatResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Profile[]> GetPersonsInChatAsync(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPersonToChat", ReplyAction="http://tempuri.org/IService/AddPersonToChatResponse")]
        bool AddPersonToChat(int chatId, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPersonToChat", ReplyAction="http://tempuri.org/IService/AddPersonToChatResponse")]
        System.Threading.Tasks.Task<bool> AddPersonToChatAsync(int chatId, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemovePersonFromChat", ReplyAction="http://tempuri.org/IService/RemovePersonFromChatResponse")]
        bool RemovePersonFromChat(int chatId, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemovePersonFromChat", ReplyAction="http://tempuri.org/IService/RemovePersonFromChatResponse")]
        System.Threading.Tasks.Task<bool> RemovePersonFromChatAsync(int chatId, int profileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMessage", ReplyAction="http://tempuri.org/IService/CreateMessageResponse")]
        bool CreateMessage(int profileId, string text, int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMessage", ReplyAction="http://tempuri.org/IService/CreateMessageResponse")]
        System.Threading.Tasks.Task<bool> CreateMessageAsync(int profileId, string text, int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessage", ReplyAction="http://tempuri.org/IService/GetMessageResponse")]
        PresentationTier.ServiceReference.Message GetMessage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessage", ReplyAction="http://tempuri.org/IService/GetMessageResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Message> GetMessageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessages", ReplyAction="http://tempuri.org/IService/GetMessagesResponse")]
        PresentationTier.ServiceReference.Message[] GetMessages(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessages", ReplyAction="http://tempuri.org/IService/GetMessagesResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Message[]> GetMessagesAsync(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMessage", ReplyAction="http://tempuri.org/IService/DeleteMessageResponse")]
        bool DeleteMessage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMessage", ReplyAction="http://tempuri.org/IService/DeleteMessageResponse")]
        System.Threading.Tasks.Task<bool> DeleteMessageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAccount", ReplyAction="http://tempuri.org/IService/CreateAccountResponse")]
        bool CreateAccount(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateAccount", ReplyAction="http://tempuri.org/IService/CreateAccountResponse")]
        System.Threading.Tasks.Task<bool> CreateAccountAsync(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authenticate", ReplyAction="http://tempuri.org/IService/AuthenticateResponse")]
        bool Authenticate(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authenticate", ReplyAction="http://tempuri.org/IService/AuthenticateResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateAsync(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ForgotDetails", ReplyAction="http://tempuri.org/IService/ForgotDetailsResponse")]
        bool ForgotDetails(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ForgotDetails", ReplyAction="http://tempuri.org/IService/ForgotDetailsResponse")]
        System.Threading.Tasks.Task<bool> ForgotDetailsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindAccount", ReplyAction="http://tempuri.org/IService/FindAccountResponse")]
        System.Tuple<PresentationTier.ServiceReference.Login, int> FindAccount(string what, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindAccount", ReplyAction="http://tempuri.org/IService/FindAccountResponse")]
        System.Threading.Tasks.Task<System.Tuple<PresentationTier.ServiceReference.Login, int>> FindAccountAsync(string what, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAccount", ReplyAction="http://tempuri.org/IService/UpdateAccountResponse")]
        bool UpdateAccount(int id, PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAccount", ReplyAction="http://tempuri.org/IService/UpdateAccountResponse")]
        System.Threading.Tasks.Task<bool> UpdateAccountAsync(int id, PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAccount", ReplyAction="http://tempuri.org/IService/DeleteAccountResponse")]
        bool DeleteAccount(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteAccount", ReplyAction="http://tempuri.org/IService/DeleteAccountResponse")]
        System.Threading.Tasks.Task<bool> DeleteAccountAsync(PresentationTier.ServiceReference.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProfile", ReplyAction="http://tempuri.org/IService/CreateProfileResponse")]
        bool CreateProfile(PresentationTier.ServiceReference.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProfile", ReplyAction="http://tempuri.org/IService/CreateProfileResponse")]
        System.Threading.Tasks.Task<bool> CreateProfileAsync(PresentationTier.ServiceReference.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReadProfile", ReplyAction="http://tempuri.org/IService/ReadProfileResponse")]
        PresentationTier.ServiceReference.Profile ReadProfile(string what, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReadProfile", ReplyAction="http://tempuri.org/IService/ReadProfileResponse")]
        System.Threading.Tasks.Task<PresentationTier.ServiceReference.Profile> ReadProfileAsync(string what, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateProfile", ReplyAction="http://tempuri.org/IService/UpdateProfileResponse")]
        bool UpdateProfile(int profileId, PresentationTier.ServiceReference.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateProfile", ReplyAction="http://tempuri.org/IService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateProfileAsync(int profileId, PresentationTier.ServiceReference.Profile profile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PresentationTier.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PresentationTier.ServiceReference.IService>, PresentationTier.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PresentationTier.ServiceReference.Chat CreateChat(PresentationTier.ServiceReference.Chat chat, int profileId) {
            return base.Channel.CreateChat(chat, profileId);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat> CreateChatAsync(PresentationTier.ServiceReference.Chat chat, int profileId) {
            return base.Channel.CreateChatAsync(chat, profileId);
        }
        
        public PresentationTier.ServiceReference.Chat[] GetChatsByName(string name) {
            return base.Channel.GetChatsByName(name);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat[]> GetChatsByNameAsync(string name) {
            return base.Channel.GetChatsByNameAsync(name);
        }
        
        public bool UpdateChat(PresentationTier.ServiceReference.Chat chat) {
            return base.Channel.UpdateChat(chat);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateChatAsync(PresentationTier.ServiceReference.Chat chat) {
            return base.Channel.UpdateChatAsync(chat);
        }
        
        public bool DeleteChat(int id) {
            return base.Channel.DeleteChat(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteChatAsync(int id) {
            return base.Channel.DeleteChatAsync(id);
        }
        
        public PresentationTier.ServiceReference.Chat[] GetPersonsChats(int profileId) {
            return base.Channel.GetPersonsChats(profileId);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Chat[]> GetPersonsChatsAsync(int profileId) {
            return base.Channel.GetPersonsChatsAsync(profileId);
        }
        
        public PresentationTier.ServiceReference.Profile[] GetPersonsInChat(int chatId) {
            return base.Channel.GetPersonsInChat(chatId);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Profile[]> GetPersonsInChatAsync(int chatId) {
            return base.Channel.GetPersonsInChatAsync(chatId);
        }
        
        public bool AddPersonToChat(int chatId, int profileId) {
            return base.Channel.AddPersonToChat(chatId, profileId);
        }
        
        public System.Threading.Tasks.Task<bool> AddPersonToChatAsync(int chatId, int profileId) {
            return base.Channel.AddPersonToChatAsync(chatId, profileId);
        }
        
        public bool RemovePersonFromChat(int chatId, int profileId) {
            return base.Channel.RemovePersonFromChat(chatId, profileId);
        }
        
        public System.Threading.Tasks.Task<bool> RemovePersonFromChatAsync(int chatId, int profileId) {
            return base.Channel.RemovePersonFromChatAsync(chatId, profileId);
        }
        
        public bool CreateMessage(int profileId, string text, int chatId) {
            return base.Channel.CreateMessage(profileId, text, chatId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateMessageAsync(int profileId, string text, int chatId) {
            return base.Channel.CreateMessageAsync(profileId, text, chatId);
        }
        
        public PresentationTier.ServiceReference.Message GetMessage(int id) {
            return base.Channel.GetMessage(id);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Message> GetMessageAsync(int id) {
            return base.Channel.GetMessageAsync(id);
        }
        
        public PresentationTier.ServiceReference.Message[] GetMessages(int chatId) {
            return base.Channel.GetMessages(chatId);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Message[]> GetMessagesAsync(int chatId) {
            return base.Channel.GetMessagesAsync(chatId);
        }
        
        public bool DeleteMessage(int id) {
            return base.Channel.DeleteMessage(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMessageAsync(int id) {
            return base.Channel.DeleteMessageAsync(id);
        }
        
        public bool CreateAccount(PresentationTier.ServiceReference.Login login) {
            return base.Channel.CreateAccount(login);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccountAsync(PresentationTier.ServiceReference.Login login) {
            return base.Channel.CreateAccountAsync(login);
        }
        
        public bool Authenticate(PresentationTier.ServiceReference.Login login) {
            return base.Channel.Authenticate(login);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateAsync(PresentationTier.ServiceReference.Login login) {
            return base.Channel.AuthenticateAsync(login);
        }
        
        public bool ForgotDetails(string email) {
            return base.Channel.ForgotDetails(email);
        }
        
        public System.Threading.Tasks.Task<bool> ForgotDetailsAsync(string email) {
            return base.Channel.ForgotDetailsAsync(email);
        }
        
        public System.Tuple<PresentationTier.ServiceReference.Login, int> FindAccount(string what, int by) {
            return base.Channel.FindAccount(what, by);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<PresentationTier.ServiceReference.Login, int>> FindAccountAsync(string what, int by) {
            return base.Channel.FindAccountAsync(what, by);
        }
        
        public bool UpdateAccount(int id, PresentationTier.ServiceReference.Login login) {
            return base.Channel.UpdateAccount(id, login);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAccountAsync(int id, PresentationTier.ServiceReference.Login login) {
            return base.Channel.UpdateAccountAsync(id, login);
        }
        
        public bool DeleteAccount(PresentationTier.ServiceReference.Login login) {
            return base.Channel.DeleteAccount(login);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAccountAsync(PresentationTier.ServiceReference.Login login) {
            return base.Channel.DeleteAccountAsync(login);
        }
        
        public bool CreateProfile(PresentationTier.ServiceReference.Profile profile) {
            return base.Channel.CreateProfile(profile);
        }
        
        public System.Threading.Tasks.Task<bool> CreateProfileAsync(PresentationTier.ServiceReference.Profile profile) {
            return base.Channel.CreateProfileAsync(profile);
        }
        
        public PresentationTier.ServiceReference.Profile ReadProfile(string what, int by) {
            return base.Channel.ReadProfile(what, by);
        }
        
        public System.Threading.Tasks.Task<PresentationTier.ServiceReference.Profile> ReadProfileAsync(string what, int by) {
            return base.Channel.ReadProfileAsync(what, by);
        }
        
        public bool UpdateProfile(int profileId, PresentationTier.ServiceReference.Profile profile) {
            return base.Channel.UpdateProfile(profileId, profile);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProfileAsync(int profileId, PresentationTier.ServiceReference.Profile profile) {
            return base.Channel.UpdateProfileAsync(profileId, profile);
        }
    }
}
